# Generated by Django 2.2.4 on 2020-12-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20201208_0045"), ("management", "0030_auto_20201130_1845")]

    operations = [
        migrations.AddField(
            model_name="group",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="principal",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
    ]
