# Generated by Django 2.2.4 on 2021-02-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0031_auto_20201209_1223")]

    operations = [
        # migrations.RunSQL("CREATE POLICY \"enforce_tenant\" ON management_role FOR ALL TO \"postgres\" USING ((management_role.tenant_id = (current_setting('api_tenant.id')::integer))); ALTER TABLE management_role ENABLE ROW LEVEL SECURITY;"),
        migrations.RunSQL(
            "CREATE POLICY \"enforce_tenant\" ON management_role FOR ALL USING ((management_role.tenant_id = (current_setting('api_tenant.id')::integer))); ALTER TABLE management_role FORCE ROW LEVEL SECURITY;"
        )
    ]


# CREATE POLICY "enforce_tenant" ON management_role FOR ALL TO "test" USING ((management_role.tenant_id = (current_setting('api_tenant.id')::integer))); ALTER TABLE management_role ENABLE ROW LEVEL SECURITY;

# from django.db import connection
# from management.models import Role

# with connection.cursor() as cursor:
#     cursor.execute('SET SESSION "api_tenant.id" = 2;')

# Role.objects.all()

# GRANT ALL PRIVILEGES ON TABLE management_role TO test;
